title                    : "Julien Velcin"
title_separator          : "-"
name                     : &name "Julien Velcin"
description              : &description "Professor of Computer Science at the University Lyon 2"
profile_picture          : http://scidolyse.ens-lyon.fr/sites/default/files/styles/medium/public/2019-02/julienvelcin.jpg 
author_profile: true

#theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
