site_name: Cours LLM & Transformers
site_author: Julien Velcin

theme:
  name: material
  features:
    - navigation.tabs # Crée de jolis onglets en haut

# Extensions pour le code (PyTorch) et les mathématiques (LaTeX)
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

# Nécessaire pour afficher le LaTeX proprement
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js